"""Remove tool_name and tool_call_id columns

Revision ID: d48cd17b5899
Revises: 20260316_0002
Create Date: 2026-03-31 02:00:01.335212
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'd48cd17b5899'
down_revision: Union[str, None] = '20260316_0002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("""
        DROP INDEX uk_session_seq ON session_messages
    """)
    with op.batch_alter_table('session_messages') as batch_op:
        batch_op.alter_column('id',
                   existing_type=mysql.BIGINT(unsigned=True),
                   type_=sa.Integer(),
                   existing_nullable=False,
                   autoincrement=True)
        batch_op.alter_column('content',
                   existing_type=mysql.LONGTEXT(),
                   type_=sa.Text(),
                   existing_nullable=False)
        batch_op.alter_column('metadata_json',
                   existing_type=mysql.LONGTEXT(),
                   type_=sa.Text(),
                   existing_nullable=True)
        batch_op.drop_column('tool_name')
        batch_op.drop_column('tool_call_id')
    with op.batch_alter_table('sessions') as batch_op:
        batch_op.alter_column('id',
                   existing_type=mysql.BIGINT(unsigned=True),
                   type_=sa.Integer(),
                   existing_nullable=False,
                   autoincrement=True)
        batch_op.alter_column('system_prompt',
                   existing_type=mysql.LONGTEXT(),
                   type_=sa.Text(),
                   existing_nullable=True)
        batch_op.alter_column('metadata_json',
                   existing_type=mysql.LONGTEXT(),
                   type_=sa.Text(),
                   existing_nullable=True)
        batch_op.alter_column('agent_config_json',
                   existing_type=mysql.LONGTEXT(),
                   type_=sa.Text(),
                   existing_nullable=True)
        batch_op.alter_column('read_cache_json',
                   existing_type=mysql.LONGTEXT(),
                   type_=sa.Text(),
                   existing_nullable=True)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sessions', 'read_cache_json',
               existing_type=sa.Text(),
               type_=mysql.LONGTEXT(),
               existing_nullable=True)
    op.alter_column('sessions', 'agent_config_json',
               existing_type=sa.Text(),
               type_=mysql.LONGTEXT(),
               existing_nullable=True)
    op.alter_column('sessions', 'metadata_json',
               existing_type=sa.Text(),
               type_=mysql.LONGTEXT(),
               existing_nullable=True)
    op.alter_column('sessions', 'system_prompt',
               existing_type=sa.Text(),
               type_=mysql.LONGTEXT(),
               existing_nullable=True)
    op.alter_column('sessions', 'id',
               existing_type=sa.Integer(),
               type_=mysql.BIGINT(unsigned=True),
               existing_nullable=False,
               autoincrement=True)
    op.add_column('session_messages', sa.Column('tool_call_id', mysql.VARCHAR(length=128), nullable=True))
    op.add_column('session_messages', sa.Column('tool_name', mysql.VARCHAR(length=128), nullable=True))
    op.create_index(op.f('uk_session_seq'), 'session_messages', ['session_id', 'seq_no'], unique=True)
    op.alter_column('session_messages', 'metadata_json',
               existing_type=sa.Text(),
               type_=mysql.LONGTEXT(),
               existing_nullable=True)
    op.alter_column('session_messages', 'content',
               existing_type=sa.Text(),
               type_=mysql.LONGTEXT(),
               existing_nullable=False)
    op.alter_column('session_messages', 'id',
               existing_type=sa.Integer(),
               type_=mysql.BIGINT(unsigned=True),
               existing_nullable=False,
               autoincrement=True)
    # ### end Alembic commands ###
